### ISSUE TITLE
reset command not working

### ISSUE THREAD

**Issue by Bikash-sah** [tacacsgui/tgui_passwd_reset#1]
when i try run reset command it give below error. please help on that error

root@tacgui:~# php /opt/tacacsgui/web/api/tgui_passwd_reset.php

####################################
Wellcome to password restoring tool!
####################################

Enter Username: user_test
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'tgui_user'@'localhost' (using password: YES) in /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40
Stack trace:
#0 /opt/tacacsgui/web/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(40): PDO->__construct('mysql:host=loca...', 'tgui_user', 'G9FApaJEdrY}MD9...', Array)
#1 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(67): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'tgui_user', 'G9FApaJEdrY}MD9...', Array)
#2 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'tgui_user', 'G9FApaJEdrY}MD9...', Array)
#3 /opt/tacacsgui/web/api/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#4 /opt/tacacsgui/web/api/vendor/illumin in /opt/tacacsgui/web/api/vendor/illuminate/database/Connection.php on line 664

![image](https://github.com/user-attachments/assets/3f00ac36-5aaa-42f0-9565-9f7aa6359e03)

**Comment by sSiDs** [comment]
same
